# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: 'java:8'

# The size of the persistent disk of the application (in MB).
disk: 2048

variables:
    env:
        JAVA_OPTS: '-Djava.util.prefs.systemRoot=/app/.java -Djava.util.prefs.userRoot=/app/.java/.userPrefs'

hooks:
    build: |
      set -e
      unset NPM_CONFIG_PREFIX
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | dash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm current
      nvm install 10.10.0
      nvm use 10.10.0
      npm install
    deploy: |
      unset NPM_CONFIG_PREFIX
      nvm use 10.10.0

mounts:
    "/.java": "shared:files/java"
    "/gatling/target": "shared:files/gatling-target"
    "/web": "shared:files/gatling-results"
    run:
      source: local
      source_path: run

web:
    commands:
        start: "npm run run"
